// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZoologicoApiWeb.Data;

#nullable disable

namespace ZoologicoApiWeb.Migrations.BDTicket
{
    [DbContext(typeof(BDTicketContext))]
    [Migration("20230716222629_inicioTicket")]
    partial class inicioTicket
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AplicacionWeb_1_GG_ER.Models.AddTickets", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.ToTable("AddTickets");
                });

            modelBuilder.Entity("AplicacionWeb_1_GG_ER.Models.Promocion", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"), 1L, 1);

                    b.Property<int?>("AddTicketsTicketId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPromo")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("PromoId");

                    b.HasIndex("AddTicketsTicketId");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("AplicacionWeb_1_GG_ER.Models.Promocion", b =>
                {
                    b.HasOne("AplicacionWeb_1_GG_ER.Models.AddTickets", "AddTickets")
                        .WithMany("Promociones")
                        .HasForeignKey("AddTicketsTicketId");

                    b.Navigation("AddTickets");
                });

            modelBuilder.Entity("AplicacionWeb_1_GG_ER.Models.AddTickets", b =>
                {
                    b.Navigation("Promociones");
                });
#pragma warning restore 612, 618
        }
    }
}
